In [ ]:
import fitz
import pdfplumber
import pandas as pd

pdf_path = r"D:\guvi final project\personal_financial_transcactions.pdf"
transactions = []

# 1. Extract text using PyMuPDF
doc = fitz.open(pdf_path)
for page in doc:
    text = page.get_text("text")
    print("Raw text:", text[:300])  # quick check
doc.close()


# 4. Save structured data
df.to_csv("upi_transactions.csv", index=False)

Raw text: date
time
amount
direction
counterpa descriptionref_id
category
02-09-2024
19:02
17734 debit
Flipkart
Payment reUTR10000 Shopping
04-09-2024
11:48
17785 debit
Uber
Payment reUTR10000 Transport
04-09-2024
23:55
40113 credit
Company PPayment reUTR10000 Salary
04-09-2024
12:56
3896 debit
Airtel
Payment
Raw text: 04-10-2024
07:07
16287 debit
Self Accou Payment reUTR10004 Transfer
04-10-2024
01:06
22208 debit
House Ow Payment reUTR10005 Rent
04-10-2024
04:51
42602 debit
SBI Securit Payment reUTR10005 Investment
05-10-2024
23:07
19266 debit
Netflix
Payment reUTR10005 Entertainment
05-10-2024
09:17
16008 debit

Raw text: 06-11-2024
07:47
26852 credit
Company PPayment reUTR10009 Salary
06-11-2024
01:00
7940 debit
TNEB
Payment reUTR10010 Bills
07-11-2024
13:28
32584 credit
Company PPayment reUTR10010 Salary
08-11-2024
22:50
9971 debit
Airtel
Payment reUTR10010 Bills
08-11-2024
01:01
2803 debit
Friend TranPayment reUTR
Raw text: 14-12-2024
23:31
9799 debit
Friend TranPayment reUTR10014 Transfer
15-12-2024
05:02
4406 debit
Rapido
Payment reUTR10015 Transport
17-12-2024
00:24
11841 debit
Zomato
Payment reUTR10015 Food
17-12-2024
09:23
9907 debit
House Ow Payment reUTR10015 Rent
17-12-2024
23:09
6829 debit
Amazon
Payment reUTR
Raw text: 13-01-2025
04:53
16050 debit
Friend TranPayment reUTR10019 Transfer
15-01-2025
10:26
24343 debit
Mutual FunPayment reUTR10020 Investment
15-01-2025
09:14
11321 debit
Swiggy
Payment reUTR10020 Food
15-01-2025
15:36
15024 debit
Myntra
Payment reUTR10020 Shopping
17-01-2025
14:35
17742 debit
Hotstar
Pa
Raw text: 17-02-2025
08:16
37079 debit
House Ow Payment reUTR10024 Rent
17-02-2025
22:31
15349 debit
BSNL
Payment reUTR10025 Bills
18-02-2025
15:38
17270 debit
BigBasket Payment reUTR10025 Groceries
18-02-2025
07:54
17898 debit
BookMyShPayment reUTR10025 Entertainment
18-02-2025
06:29
18067 debit
Netflix
Paym
Raw text: 17-03-2025
02:00
16611 debit
Self Accou Payment reUTR10029 Transfer
18-03-2025
22:00
33233 debit
SBI Securit Payment reUTR10030 Investment
18-03-2025
23:03
13006 debit
Hotstar
Payment reUTR10030 Entertainment
19-03-2025
20:37
16775 credit
Company PPayment reUTR10030 Salary
19-03-2025
17:41
2833 debi
Raw text: 20-04-2025
16:15
10442 credit
Company PPayment reUTR10034 Salary
20-04-2025
16:24
16838 debit
Zomato
Payment reUTR10035 Food
21-04-2025
18:24
17457 debit
Ola
Payment reUTR10035 Transport
21-04-2025
03:23
43587 debit
Mutual FunPayment reUTR10035 Investment
23-04-2025
19:01
2140 debit
Friend TranPayme
Raw text: 23-05-2025
11:45
19961 debit
Uber
Payment reUTR10039 Transport
24-05-2025
17:18
9455 debit
Ola
Payment reUTR10040 Transport
24-05-2025
19:25
15007 debit
Zepto
Payment reUTR10040 Groceries
26-05-2025
18:36
19636 debit
Zepto
Payment reUTR10040 Groceries
26-05-2025
15:37
12490 debit
Zomato
Payment reUT
Raw text: 23-06-2025
10:50
46931 credit
Company PPayment reUTR10044 Salary
27-06-2025
05:22
19172 debit
Friend TranPayment reUTR10045 Transfer
28-06-2025
19:21
8936 debit
BSNL
Payment reUTR10045 Bills
29-06-2025
03:41
7117 debit
Self Accou Payment reUTR10045 Transfer
29-06-2025
04:04
14399 debit
Netflix
Payme
Raw text: 27-07-2025
14:59
10806 debit
Self Accou Payment reUTR10049 Transfer
27-07-2025
17:39
15057 debit
BookMyShPayment reUTR10050 Entertainment
29-07-2025
11:58
28187 debit
Flat Rent
Payment reUTR10050 Rent
31-07-2025
01:35
12435 debit
Mutual FunPayment reUTR10050 Investment
31-07-2025
23:59
45642 debit
S

NameError: name 'page_num' is not defined

In [6]:
with pdfplumber.open(pdf_path) as pdf:
    for page_num, page in enumerate(pdf.pages):
        table = page.extract_table()
        print(f"Page {page_num + 1}: Table extracted -> {table}")
        if table:
            for row in table[1:]:
                transactions.append(row)

Page 1: Table extracted -> None
Page 2: Table extracted -> None
Page 3: Table extracted -> None
Page 4: Table extracted -> None
Page 5: Table extracted -> None
Page 6: Table extracted -> None
Page 7: Table extracted -> None
Page 8: Table extracted -> None
Page 9: Table extracted -> None
Page 10: Table extracted -> None
Page 11: Table extracted -> None

In [7]:
with pdfplumber.open(pdf_path) as pdf:
    for page_num, page in enumerate(pdf.pages):
        text = page.extract_text()
        print(f"Page {page_num + 1} Text:\n{text[:500]}")  # Preview first 500 characters

Page 1 Text:
date time amount direction counterpardtyescriptionref_id category
02-09-2024 19:02 17734 debit Flipkart Payment reUlaTtRe1d0 t0o0 F0l0iSphkoaprtping
04-09-2024 11:48 17785 debit Uber Payment reUlaTtRe1d0 t0o0 U01bTerransport
04-09-2024 23:55 40113 credit Company PPvat yLmtdent reUlaTtRe1d0 t0o0 C0o2Smalpaaryny Pvt Ltd
04-09-2024 12:56 3896 debit Airtel Payment reUlaTtRe1d0 t0o0 A0i3rBtiellls
06-09-2024 09:46 8167 debit Self AccounPtayment reUlaTtRe1d0 t0o0 S0e4Tlfr aAncscfoeurnt
06-09-2024 20:06
Page 2 Text:
04-10-2024 07:07 16287 debit Self AccounPtayment reUlaTtRe1d0 t0o0 S4e9Tlfr aAncscfoeurnt
04-10-2024 01:06 22208 debit House OwnPearyment reUlaTtRe1d0 t0o0 H50oRuesnet Owner
04-10-2024 04:51 42602 debit SBI SecuritiPeasyment reUlaTtRe1d0 t0o0 S5B1IIn Sveecsutmriteienst
05-10-2024 23:07 19266 debit Netflix Payment reUlaTtRe1d0 t0o0 N52eEtnfltiexrtainment
05-10-2024 09:17 16008 debit Amazon Payment reUlaTtRe1d0 t0o0 A5m3Shaozopnping
05-10-2024 05:12 19968 debit Dominos Payment reUlaTtRe1d0 t0o0 D5
Page 3 Text:
06-11-2024 07:47 26852 credit Company PPvat yLmtdent reUlaTtRe1d0 t0o0 C9o9Smalpaaryny Pvt Ltd
06-11-2024 01:00 7940 debit TNEB Payment reUlaTtRe1d0 t0o1 T0N0BEilBls
07-11-2024 13:28 32584 credit Company PPvat yLmtdent reUlaTtRe1d0 t0o1 C0o1Smalpaaryny Pvt Ltd
08-11-2024 22:50 9971 debit Airtel Payment reUlaTtRe1d0 t0o1 A0i2rBtiellls
08-11-2024 01:01 2803 debit Friend TranPsafeyrment reUlaTtRe1d0 t0o1 F0r3iTernadn sTfrearnsfer
08-11-2024 14:16 19806 debit BigBasket Payment reUlaTtRe1d0 t0o1 B0i4
Page 4 Text:
14-12-2024 23:31 9799 debit Friend TranPsafeyrment reUlaTtRe1d0 t0o1 F4r9iTernadn sTfrearnsfer
15-12-2024 05:02 4406 debit Rapido Payment reUlaTtRe1d0 t0o1 R5a0Tpriadnosport
17-12-2024 00:24 11841 debit Zomato Payment reUlaTtRe1d0 t0o1 Z5o1Fmoaotdo
17-12-2024 09:23 9907 debit House OwnPearyment reUlaTtRe1d0 t0o1 H52oRuesnet Owner
17-12-2024 23:09 6829 debit Amazon Payment reUlaTtRe1d0 t0o1 A5m3Shaozopnping
18-12-2024 16:46 12816 debit BSNL Payment reUlaTtRe1d0 t0o1 B5S4BNilLls
18-12-2024 12:06 3
Page 5 Text:
13-01-2025 04:53 16050 debit Friend TranPsafeyrment reUlaTtRe1d0 t0o1 F9r9iTernadn sTfrearnsfer
15-01-2025 10:26 24343 debit Mutual FunPdayment reUlaTtRe1d0 t0o2 M00Iuntvueasl tFmuenndt
15-01-2025 09:14 11321 debit Swiggy Payment reUlaTtRe1d0 t0o2 S0w1Fiogogyd
15-01-2025 15:36 15024 debit Myntra Payment reUlaTtRe1d0 t0o2 M02Syhnotrpaping
17-01-2025 14:35 17742 debit Hotstar Payment reUlaTtRe1d0 t0o2 H03oEtnsttearrtainment
17-01-2025 09:32 14678 debit BookMyShoPwayment reUlaTtRe1d0 t0o2 B0o4Eonkt
Page 6 Text:
17-02-2025 08:16 37079 debit House OwnPearyment reUlaTtRe1d0 t0o2 H49oRuesnet Owner
17-02-2025 22:31 15349 debit BSNL Payment reUlaTtRe1d0 t0o2 B5S0BNilLls
18-02-2025 15:38 17270 debit BigBasket Payment reUlaTtRe1d0 t0o2 B5i1gGBraosckeerties
18-02-2025 07:54 17898 debit BookMyShoPwayment reUlaTtRe1d0 t0o2 B5o2EonktMerytaShinomwent
18-02-2025 06:29 18067 debit Netflix Payment reUlaTtRe1d0 t0o2 N53eEtnfltiexrtainment
19-02-2025 22:18 17196 debit BSNL Payment reUlaTtRe1d0 t0o2 B5S4BNilLls
19-02-202
Page 7 Text:
17-03-2025 02:00 16611 debit Self AccounPtayment reUlaTtRe1d0 t0o2 S9e9Tlfr aAncscfoeurnt
18-03-2025 22:00 33233 debit SBI SecuritiPeasyment reUlaTtRe1d0 t0o3 S0B0IIn Sveecsutmriteienst
18-03-2025 23:03 13006 debit Hotstar Payment reUlaTtRe1d0 t0o3 H01oEtnsttearrtainment
19-03-2025 20:37 16775 credit Company PPvat yLmtdent reUlaTtRe1d0 t0o3 C0o2Smalpaaryny Pvt Ltd
19-03-2025 17:41 2833 debit BookMyShoPwayment reUlaTtRe1d0 t0o3 B0o3EonktMerytaShinomwent
19-03-2025 14:33 16659 debit BigBasket Paym
Page 8 Text:
20-04-2025 16:15 10442 credit Company PPvat yLmtdent reUlaTtRe1d0 t0o3 C4o9Smalpaaryny Pvt Ltd
20-04-2025 16:24 16838 debit Zomato Payment reUlaTtRe1d0 t0o3 Z5o0Fmoaotdo
21-04-2025 18:24 17457 debit Ola Payment reUlaTtRe1d0 t0o3 O51lTaransport
21-04-2025 03:23 43587 debit Mutual FunPdayment reUlaTtRe1d0 t0o3 M52Iuntvueasl tFmuenndt
23-04-2025 19:01 2140 debit Friend TranPsafeyrment reUlaTtRe1d0 t0o3 F5r3iTernadn sTfrearnsfer
23-04-2025 21:57 13591 debit Zepto Payment reUlaTtRe1d0 t0o3 Z5e4Gprtoo
Page 9 Text:
23-05-2025 11:45 19961 debit Uber Payment reUlaTtRe1d0 t0o3 U99bTerransport
24-05-2025 17:18 9455 debit Ola Payment reUlaTtRe1d0 t0o4 O00lTaransport
24-05-2025 19:25 15007 debit Zepto Payment reUlaTtRe1d0 t0o4 Z0e1Gprtooceries
26-05-2025 18:36 19636 debit Zepto Payment reUlaTtRe1d0 t0o4 Z0e2Gprtooceries
26-05-2025 15:37 12490 debit Zomato Payment reUlaTtRe1d0 t0o4 Z0o3Fmoaotdo
26-05-2025 05:02 13990 debit Blinkit Payment reUlaTtRe1d0 t0o4 B0l4iGnrkoitceries
27-05-2025 14:22 14438 debit Self Acco
Page 10 Text:
23-06-2025 10:50 46931 credit Company PPvat yLmtdent reUlaTtRe1d0 t0o4 C4o9Smalpaaryny Pvt Ltd
27-06-2025 05:22 19172 debit Friend TranPsafeyrment reUlaTtRe1d0 t0o4 F5r0iTernadn sTfrearnsfer
28-06-2025 19:21 8936 debit BSNL Payment reUlaTtRe1d0 t0o4 B5S1BNilLls
29-06-2025 03:41 7117 debit Self AccounPtayment reUlaTtRe1d0 t0o4 S5e2Tlfr aAncscfoeurnt
29-06-2025 04:04 14399 debit Netflix Payment reUlaTtRe1d0 t0o4 N53eEtnfltiexrtainment
30-06-2025 18:45 16716 debit Ola Payment reUlaTtRe1d0 t0o4 O54l
Page 11 Text:
27-07-2025 14:59 10806 debit Self AccounPtayment reUlaTtRe1d0 t0o4 S9e9Tlfr aAncscfoeurnt
27-07-2025 17:39 15057 debit BookMyShoPwayment reUlaTtRe1d0 t0o5 B0o0EonktMerytaShinomwent
29-07-2025 11:58 28187 debit Flat Rent Payment reUlaTtRe1d0 t0o5 F0l1aRte Rnetnt
31-07-2025 01:35 12435 debit Mutual FunPdayment reUlaTtRe1d0 t0o5 M02Iuntvueasl tFmuenndt
31-07-2025 23:59 45642 debit SBI SecuritiPeasyment reUlaTtRe1d0 t0o5 S0B3IIn Sveecsutmriteienst
31-07-2025 10:46 17784 debit Netflix Payment reUlaTt

In [9]:
import pandas as pd

# Define columns (based on the data structure in the PDF)
columns = ["Date", "Time", "Amount", "Direction", "Counterparty", "Description", "Ref_ID", "Category"]

df = pd.DataFrame(transactions, columns=columns)

# Preview the first few rows
print(df.head())

Empty DataFrame
Columns: [Date, Time, Amount, Direction, Counterparty, Description, Ref_ID, Category]
Index: []

In [10]:
# 4. Save structured data
df.to_csv("upi_transactions.csv", index=False)

In [8]:
df.head()

Empty DataFrame
Columns: [Date, Time, Amount, Direction, Counterparty, Description, Ref_ID, Category]
Index: []

In [11]:
import re
import pandas as pd
import pdfplumber

transactions = []

with pdfplumber.open(pdf_path) as pdf:
    for page in pdf.pages:
        text = page.extract_text()
        for line in text.split('\n'):
            # Regex pattern to match a valid transaction line
            pattern = r'(\d{2}-\d{2}-\d{4}) (\d{2}:\d{2}) (\d+) (debit|credit) (\w+) (.+?) (UTR\d+) (\w+)'
            match = re.match(pattern, line)
            if match:
                transactions.append(list(match.groups()))

# Define columns
columns = ["Date", "Time", "Amount", "Direction", "Counterparty", "Description", "Ref_ID", "Category"]
df = pd.DataFrame(transactions, columns=columns)

# Preview results
print(df.head())

Empty DataFrame
Columns: [Date, Time, Amount, Direction, Counterparty, Description, Ref_ID, Category]
Index: []

In [13]:
import pdfplumber

pdf_path = r"D:\guvi final project\personal_financial_transcactions.pdf"

with pdfplumber.open(pdf_path) as pdf:
    first_page = pdf.pages[0]
    text = first_page.extract_text()
    lines = text.split('\n')

# Print first 20 lines to inspect their structure
for i, line in enumerate(lines[:20]):
    print(f"{i+1}: {line}")

1: date time amount direction counterpardtyescriptionref_id category
2: 02-09-2024 19:02 17734 debit Flipkart Payment reUlaTtRe1d0 t0o0 F0l0iSphkoaprtping
3: 04-09-2024 11:48 17785 debit Uber Payment reUlaTtRe1d0 t0o0 U01bTerransport
4: 04-09-2024 23:55 40113 credit Company PPvat yLmtdent reUlaTtRe1d0 t0o0 C0o2Smalpaaryny Pvt Ltd
5: 04-09-2024 12:56 3896 debit Airtel Payment reUlaTtRe1d0 t0o0 A0i3rBtiellls
6: 06-09-2024 09:46 8167 debit Self AccounPtayment reUlaTtRe1d0 t0o0 S0e4Tlfr aAncscfoeurnt
7: 06-09-2024 20:06 19836 debit Myntra Payment reUlaTtRe1d0 t0o0 M05Syhnotrpaping
8: 06-09-2024 07:56 49949 credit Company PPvat yLmtdent reUlaTtRe1d0 t0o0 C0o6Smalpaaryny Pvt Ltd
9: 07-09-2024 20:41 21433 debit Flat Rent Payment reUlaTtRe1d0 t0o0 F0l7aRte Rnetnt
10: 10-09-2024 11:58 6166 debit Amazon Payment reUlaTtRe1d0 t0o0 A0m8Shaozopnping
11: 10-09-2024 22:02 12352 debit Zomato Payment reUlaTtRe1d0 t0o0 Z0o9Fmoaotdo
12: 10-09-2024 09:08 29727 debit SBI SecuritiPeasyment reUlaTtRe1d0 t0o0 S1B0IIn Sveecsutmriteienst
13: 12-09-2024 14:59 14230 debit Zepto Payment reUlaTtRe1d0 t0o0 Z1e1Gprtooceries
14: 12-09-2024 03:37 47806 credit Company PPvat yLmtdent reUlaTtRe1d0 t0o0 C1o2Smalpaaryny Pvt Ltd
15: 12-09-2024 10:42 30760 debit SBI SecuritiPeasyment reUlaTtRe1d0 t0o0 S1B3IIn Sveecsutmriteienst
16: 13-09-2024 14:05 12054 debit BookMyShoPwayment reUlaTtRe1d0 t0o0 B1o4EonktMerytaShinomwent
17: 13-09-2024 21:53 7809 debit Hotstar Payment reUlaTtRe1d0 t0o0 H15oEtnsttearrtainment
18: 13-09-2024 10:59 2141 debit Airtel Payment reUlaTtRe1d0 t0o0 A1i6rBtiellls
19: 14-09-2024 19:39 18446 debit TNEB Payment reUlaTtRe1d0 t0o0 T1N7BEilBls
20: 14-09-2024 17:29 938 debit BookMyShoPwayment reUlaTtRe1d0 t0o0 B1o8EonktMerytaShinomwent

In [14]:
df.head()

Empty DataFrame
Columns: [Date, Time, Amount, Direction, Counterparty, Description, Ref_ID, Category]
Index: []

In [15]:
df.tail()

Empty DataFrame
Columns: [Date, Time, Amount, Direction, Counterparty, Description, Ref_ID, Category]
Index: []

In [1]:
import pdfplumber
import pandas as pd

# Path to your PDF
pdf_path = r"D:\guvi final project\personal_financial_transcactions.pdf"

# Store transactions
all_data = []

with pdfplumber.open(pdf_path) as pdf:
    for page in pdf.pages:
        table = page.extract_table()
        if table:
            # Skip the header if it repeats
            for row in table:
                if row[0].lower() == "date":  
                    continue
                all_data.append(row)

# Convert to DataFrame
columns = ["date", "time", "amount", "direction", "counterparty", "description", "ref_id", "category"]
df = pd.DataFrame(all_data, columns=columns)

# Convert numeric column
df["amount"] = pd.to_numeric(df["amount"], errors="coerce")

# Save as CSV for later use
df.to_csv("transactions.csv", index=False)

print("Data extracted successfully! Sample:")
print(df.head())

Data extracted successfully! Sample:
Empty DataFrame
Columns: [date, time, amount, direction, counterparty, description, ref_id, category]
Index: []

In [2]:
df.head()

Empty DataFrame
Columns: [date, time, amount, direction, counterparty, description, ref_id, category]
Index: []

In [3]:
import fitz  # PyMuPDF
import pandas as pd
import re

pdf_path = r"D:\guvi final project\personal_financial_transcactions.pdf"

transactions = []

# Open PDF with fitz
doc = fitz.open(pdf_path)
for page in doc:
    text = page.get_text("text")
    lines = text.split("\n")
    
    for line in lines:
        # Match: date time amount direction counterparty...ref_id category
        match = re.match(r"(\d{2}-\d{2}-\d{4})\s+(\d{2}:\d{2})\s+(\d+)\s+(debit|credit)\s+(.*?)(UTR\d+)([A-Za-z]+)", line)
        if match:
            date, time, amount, direction, counterparty_desc, ref_id, category = match.groups()
            
            # Split counterparty and description
            if "Payment related to" in counterparty_desc:
                parts = counterparty_desc.split("Payment related to")
                counterparty = parts[0].strip()
                description = "Payment related to " + parts[1].strip()
            else:
                counterparty = counterparty_desc.strip()
                description = ""
            
            transactions.append([date, time, amount, direction, counterparty, description, ref_id, category])

doc.close()

# Convert to DataFrame
columns = ["date", "time", "amount", "direction", "counterparty", "description", "ref_id", "category"]
df = pd.DataFrame(transactions, columns=columns)

# Convert numeric columns
df["amount"] = pd.to_numeric(df["amount"], errors="coerce")

# Save as CSV
df.to_csv("transactions.csv", index=False)

print("Data extracted successfully!")
print(df.head(10))

Data extracted successfully!
Empty DataFrame
Columns: [date, time, amount, direction, counterparty, description, ref_id, category]
Index: []

In [4]:
print(df.head(10))

Empty DataFrame
Columns: [date, time, amount, direction, counterparty, description, ref_id, category]
Index: []

In [5]:
import fitz  # PyMuPDF

pdf_path = r"D:\guvi final project\personal_financial_transcactions.pdf"

doc = fitz.open(pdf_path)
for page_num, page in enumerate(doc, start=1):
    text = page.get_text("text")
    lines = text.split("\n")
    print(f"--- Page {page_num} ---")
    for i, line in enumerate(lines[:20]):  # print only first 20 lines
        print(i, line)
doc.close()

--- Page 1 ---
0 date
1 time
2 amount
3 direction
4 counterpa descriptionref_id
5 category
6 02-09-2024
7 19:02
8 17734 debit
9 Flipkart
10 Payment reUTR10000 Shopping
11 04-09-2024
12 11:48
13 17785 debit
14 Uber
15 Payment reUTR10000 Transport
16 04-09-2024
17 23:55
18 40113 credit
19 Company PPayment reUTR10000 Salary
--- Page 2 ---
0 04-10-2024
1 07:07
2 16287 debit
3 Self Accou Payment reUTR10004 Transfer
4 04-10-2024
5 01:06
6 22208 debit
7 House Ow Payment reUTR10005 Rent
8 04-10-2024
9 04:51
10 42602 debit
11 SBI Securit Payment reUTR10005 Investment
12 05-10-2024
13 23:07
14 19266 debit
15 Netflix
16 Payment reUTR10005 Entertainment
17 05-10-2024
18 09:17
19 16008 debit
--- Page 3 ---
0 06-11-2024
1 07:47
2 26852 credit
3 Company PPayment reUTR10009 Salary
4 06-11-2024
5 01:00
6 7940 debit
7 TNEB
8 Payment reUTR10010 Bills
9 07-11-2024
10 13:28
11 32584 credit
12 Company PPayment reUTR10010 Salary
13 08-11-2024
14 22:50
15 9971 debit
16 Airtel
17 Payment reUTR10010 Bills
18 08-11-2024
19 01:01
--- Page 4 ---
0 14-12-2024
1 23:31
2 9799 debit
3 Friend TranPayment reUTR10014 Transfer
4 15-12-2024
5 05:02
6 4406 debit
7 Rapido
8 Payment reUTR10015 Transport
9 17-12-2024
10 00:24
11 11841 debit
12 Zomato
13 Payment reUTR10015 Food
14 17-12-2024
15 09:23
16 9907 debit
17 House Ow Payment reUTR10015 Rent
18 17-12-2024
19 23:09
--- Page 5 ---
0 13-01-2025
1 04:53
2 16050 debit
3 Friend TranPayment reUTR10019 Transfer
4 15-01-2025
5 10:26
6 24343 debit
7 Mutual FunPayment reUTR10020 Investment
8 15-01-2025
9 09:14
10 11321 debit
11 Swiggy
12 Payment reUTR10020 Food
13 15-01-2025
14 15:36
15 15024 debit
16 Myntra
17 Payment reUTR10020 Shopping
18 17-01-2025
19 14:35
--- Page 6 ---
0 17-02-2025
1 08:16
2 37079 debit
3 House Ow Payment reUTR10024 Rent
4 17-02-2025
5 22:31
6 15349 debit
7 BSNL
8 Payment reUTR10025 Bills
9 18-02-2025
10 15:38
11 17270 debit
12 BigBasket Payment reUTR10025 Groceries
13 18-02-2025
14 07:54
15 17898 debit
16 BookMyShPayment reUTR10025 Entertainment
17 18-02-2025
18 06:29
19 18067 debit
--- Page 7 ---
0 17-03-2025
1 02:00
2 16611 debit
3 Self Accou Payment reUTR10029 Transfer
4 18-03-2025
5 22:00
6 33233 debit
7 SBI Securit Payment reUTR10030 Investment
8 18-03-2025
9 23:03
10 13006 debit
11 Hotstar
12 Payment reUTR10030 Entertainment
13 19-03-2025
14 20:37
15 16775 credit
16 Company PPayment reUTR10030 Salary
17 19-03-2025
18 17:41
19 2833 debit
--- Page 8 ---
0 20-04-2025
1 16:15
2 10442 credit
3 Company PPayment reUTR10034 Salary
4 20-04-2025
5 16:24
6 16838 debit
7 Zomato
8 Payment reUTR10035 Food
9 21-04-2025
10 18:24
11 17457 debit
12 Ola
13 Payment reUTR10035 Transport
14 21-04-2025
15 03:23
16 43587 debit
17 Mutual FunPayment reUTR10035 Investment
18 23-04-2025
19 19:01
--- Page 9 ---
0 23-05-2025
1 11:45
2 19961 debit
3 Uber
4 Payment reUTR10039 Transport
5 24-05-2025
6 17:18
7 9455 debit
8 Ola
9 Payment reUTR10040 Transport
10 24-05-2025
11 19:25
12 15007 debit
13 Zepto
14 Payment reUTR10040 Groceries
15 26-05-2025
16 18:36
17 19636 debit
18 Zepto
19 Payment reUTR10040 Groceries
--- Page 10 ---
0 23-06-2025
1 10:50
2 46931 credit
3 Company PPayment reUTR10044 Salary
4 27-06-2025
5 05:22
6 19172 debit
7 Friend TranPayment reUTR10045 Transfer
8 28-06-2025
9 19:21
10 8936 debit
11 BSNL
12 Payment reUTR10045 Bills
13 29-06-2025
14 03:41
15 7117 debit
16 Self Accou Payment reUTR10045 Transfer
17 29-06-2025
18 04:04
19 14399 debit
--- Page 11 ---
0 27-07-2025
1 14:59
2 10806 debit
3 Self Accou Payment reUTR10049 Transfer
4 27-07-2025
5 17:39
6 15057 debit
7 BookMyShPayment reUTR10050 Entertainment
8 29-07-2025
9 11:58
10 28187 debit
11 Flat Rent
12 Payment reUTR10050 Rent
13 31-07-2025
14 01:35
15 12435 debit
16 Mutual FunPayment reUTR10050 Investment
17 31-07-2025
18 23:59
19 45642 debit

In [8]:
# robust_extract_transactions.py
# Run this in the same environment where you run previous code.
# Make sure you have fitz (PyMuPDF). If PDF is image-only, you'll need pdf2image + pytesseract.

import fitz            # pip install pymupdf
import re
import pandas as pd
import os
import sys

pdf_path = r"D:\guvi final project\personal_financial_transcactions.pdf"  # adjust if different

def print_raw_lines(pdf_path, pages_to_show=2, lines_to_show=30):
    """Print raw text lines so you can inspect actual formatting."""
    doc = fitz.open(pdf_path)
    for page_num in range(min(len(doc), pages_to_show)):
        page = doc[page_num]
        text = page.get_text("text")
        lines = text.splitlines()
        print(f"\n--- Page {page_num+1} raw lines (first {lines_to_show}) ---")
        for i, line in enumerate(lines[:lines_to_show]):
            # show repr to reveal hidden characters/spaces
            print(i+1, repr(line))
    doc.close()

def extract_with_patterns(pdf_path, patterns):
    """Try multiple regex patterns to extract rows. Return list of rows."""
    doc = fitz.open(pdf_path)
    rows = []
    for page in doc:
        text = page.get_text("text")
        if not text or text.strip()=="":
            continue
        for line in text.splitlines():
            for pat in patterns:
                m = re.search(pat, line)
                if m:
                    rows.append(m.groups())
                    break
    doc.close()
    return rows

def try_ocr(pdf_path):
    """Fallback: OCR pages to text and return lines (requires pdf2image & pytesseract)."""
    try:
        from pdf2image import convert_from_path  # pip install pdf2image
        import pytesseract                        # pip install pytesseract
    except Exception as e:
        print("OCR fallback unavailable (pdf2image/pytesseract not installed).", e)
        return []

    print("Starting OCR fallback (slower). Make sure Tesseract is installed on your system.")
    pages = convert_from_path(pdf_path, dpi=200)
    ocr_texts = []
    for i, page_image in enumerate(pages):
        txt = pytesseract.image_to_string(page_image)
        lines = txt.splitlines()
        print(f"OCR page {i+1} first 10 lines: ")
        for l in lines[:10]:
            print(repr(l))
        ocr_texts.append("\n".join(lines))
    return ocr_texts

# --- Step A: show raw lines so you (and we) know the format ---
print("1) Printing raw lines from the PDF. Inspect these to see exact formatting:")
if not os.path.exists(pdf_path):
    print("ERROR: PDF not found at", pdf_path)
    sys.exit(1)
print_raw_lines(pdf_path, pages_to_show=2, lines_to_show=40)

# --- Step B: try multiple patterns (covers common line formats) ---
# We'll attempt patterns that capture:
#   date time amount direction counterparty (Payment related to ...)? UTRxxx category
patterns = [
    # pattern 1: same as earlier, but made flexible about spacing and optional description text
    r"(\d{2}-\d{2}-\d{4})\s+(\d{2}:\d{2})\s+(\d+)\s+(debit|credit)\s+(.*?)\s*(?:Payment related to\s*(.*?))?\s*(UTR\d+)\s*([A-Za-z]+)",
    # pattern 2: sometimes description and UTR are glued (no space between UTR and category)
    r"(\d{2}-\d{2}-\d{4})\s+(\d{2}:\d{2})\s+(\d+)\s+(debit|credit)\s+(.*?)(UTR\d+)([A-Za-z]+)",
    # pattern 3: minimal greedy split: date time amount dir rest category at end
    r"(\d{2}-\d{2}-\d{4})\s+(\d{2}:\d{2})\s+(\d+)\s+(debit|credit)\s+(.*)\s+(UTR\d+)\s*([A-Za-z]+)$",
    # pattern 4: if category is absent or numeric; capture everything to inspect
    r"(\d{2}-\d{2}-\d{4})\s+(\d{2}:\d{2})\s+(\d+)\s+(debit|credit)\s+(.*)",
]

print("\n2) Trying multiple regex patterns to extract transactions...")
rows = extract_with_patterns(pdf_path, patterns)

# If none found, report and suggest OCR
if not rows:
    print("\nNo matches found with text extraction. Possible causes:")
    print("- PDF may be image-based (scanned) so text extraction returns empty or garbage.")
    print("- The actual line format differs; check the raw lines above for differences.")
    # Try OCR fallback
    ocr_texts = try_ocr(pdf_path)
    ocr_rows = []
    if ocr_texts:
        # try the same patterns over OCR text
        for ocr_text in ocr_texts:
            for line in ocr_text.splitlines():
                for pat in patterns:
                    m = re.search(pat, line)
                    if m:
                        ocr_rows.append(m.groups())
                        break
    if ocr_rows:
        rows = ocr_rows
        print(f"\nOCR-based extraction found {len(rows)} matches.")
    else:
        print("\nAfter OCR, still no matches. Paste here a few raw lines (use print_raw_lines output) and I'll adapt the pattern.")
        sys.exit(0)

# --- Step C: normalize extracted tuples into DataFrame columns ---
print(f"\nFound {len(rows)} raw regex matches. Converting to dataframe...")
normalized = []
for r in rows:
    # Different patterns produce different tuple shapes — handle them.
    # We'll try to safely map fields: date,time,amount,direction,counterparty,description,ref_id,category
    date = time = amount = direction = counterparty = description = ref_id = category = None
    if len(r) >= 8:
        date, time, amount, direction, cp1, desc1, ref_id, category = r[:8]
        # sometimes cp1 contains 'merchant' and desc1 empty. reassemble:
        if desc1 is None or desc1.strip()=="":
            # if cp1 contains "Payment related to", split it
            if "Payment related to" in cp1:
                parts = cp1.split("Payment related to")
                counterparty = parts[0].strip()
                description = "Payment related to " + parts[1].strip()
            else:
                counterparty = cp1.strip()
                description = ""
        else:
            counterparty = cp1.strip()
            description = desc1.strip()
    elif len(r) == 7:
        date, time, amount, direction, cp, ref_id, category = r
        counterparty = cp.strip()
        description = ""
    elif len(r) == 5:
        date, time, amount, direction, rest = r
        # try to split rest into counterparty/ref/category heuristically
        # e.g., 'Flipkart Payment related to FlipkartUTR100000Shopping'
        m = re.search(r"(.*?)(UTR\d+)([A-Za-z]+)$", rest)
        if m:
            counterparty_desc = m.group(1).strip()
            ref_id = m.group(2)
            category = m.group(3)
            if "Payment related to" in counterparty_desc:
                parts = counterparty_desc.split("Payment related to")
                counterparty = parts[0].strip()
                description = "Payment related to " + parts[1].strip()
            else:
                # split first token as counterparty
                tokens = counterparty_desc.split()
                counterparty = tokens[0]
                description = counterparty_desc
        else:
            counterparty = rest.strip()
            description = ""
    else:
        # unknown shape: stash the joined values in description to inspect later
        joined = " | ".join([str(x) for x in r])
        date = r[0] if len(r)>0 else None
        counterparty = joined
        description = joined

    normalized.append({
        "date": date,
        "time": time,
        "amount": amount,
        "direction": direction,
        "counterparty": counterparty,
        "description": description,
        "ref_id": ref_id,
        "category": category
    })

df = pd.DataFrame(normalized, columns=["date","time","amount","direction","counterparty","description","ref_id","category"])

# clean numeric
df["amount"] = pd.to_numeric(df["amount"], errors="coerce")

print("\nDataFrame shape:", df.shape)
print("First 10 rows (for inspection):")
print(df.head(10))

# Save CSV
out_csv = "transactions_extracted.csv"
df.to_csv(out_csv, index=False)
print(f"\nSaved extracted transactions to {out_csv}")

# Helpful tip: if df is empty, open the saved CSV to see intermediate content.
if df.empty:
    print("\nDataFrame is still empty after all attempts. Two likely reasons:")
    print("1) The PDF text format is quite different — check the raw lines printed above.")
    print("2) The file is image-based and OCR failed or not installed. Install tesseract and pytesseract and try again.")
else:
    print("\nSUCCESS: dataset extraction complete (or partial). You can now proceed to cleaning & analysis.")

1) Printing raw lines from the PDF. Inspect these to see exact formatting:

--- Page 1 raw lines (first 40) ---
1 'date'
2 'time'
3 'amount'
4 'direction'
5 'counterpa descriptionref_id'
6 'category'
7 '02-09-2024'
8 '19:02'
9 '17734 debit'
10 'Flipkart'
11 'Payment reUTR10000 Shopping'
12 '04-09-2024'
13 '11:48'
14 '17785 debit'
15 'Uber'
16 'Payment reUTR10000 Transport'
17 '04-09-2024'
18 '23:55'
19 '40113 credit'
20 'Company PPayment reUTR10000 Salary'
21 '04-09-2024'
22 '12:56'
23 '3896 debit'
24 'Airtel'
25 'Payment reUTR10000 Bills'
26 '06-09-2024'
27 '09:46'
28 '8167 debit'
29 'Self Accou Payment reUTR10000 Transfer'
30 '06-09-2024'
31 '20:06'
32 '19836 debit'
33 'Myntra'
34 'Payment reUTR10000 Shopping'
35 '06-09-2024'
36 '07:56'
37 '49949 credit'
38 'Company PPayment reUTR10000 Salary'
39 '07-09-2024'
40 '20:41'

--- Page 2 raw lines (first 40) ---
1 '04-10-2024'
2 '07:07'
3 '16287 debit'
4 'Self Accou Payment reUTR10004 Transfer'
5 '04-10-2024'
6 '01:06'
7 '22208 debit'
8 'House Ow Payment reUTR10005 Rent'
9 '04-10-2024'
10 '04:51'
11 '42602 debit'
12 'SBI Securit Payment reUTR10005 Investment'
13 '05-10-2024'
14 '23:07'
15 '19266 debit'
16 'Netflix'
17 'Payment reUTR10005 Entertainment'
18 '05-10-2024'
19 '09:17'
20 '16008 debit'
21 'Amazon'
22 'Payment reUTR10005 Shopping'
23 '05-10-2024'
24 '05:12'
25 '19968 debit'
26 'Dominos'
27 'Payment reUTR10005 Food'
28 '07-10-2024'
29 '13:39'
30 '5635 debit'
31 'BookMyShPayment reUTR10005 Entertainment'
32 '07-10-2024'
33 '23:09'
34 '14895 debit'
35 'BSNL'
36 'Payment reUTR10005 Bills'
37 '08-10-2024'
38 '18:51'
39 '14002 debit'
40 'Friend TranPayment reUTR10005 Transfer'

2) Trying multiple regex patterns to extract transactions...

No matches found with text extraction. Possible causes:
- PDF may be image-based (scanned) so text extraction returns empty or garbage.
- The actual line format differs; check the raw lines above for differences.
Starting OCR fallback (slower). Make sure Tesseract is installed on your system.

PDFInfoNotInstalledError: Unable to get page count. Is poppler installed and in PATH?

In [ ]:
!pip install pdf2image
!pip install pytesseract

Collecting pytesseract
  Downloading pytesseract-0.3.13-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: packaging>=21.3 in c:\users\admin\anaconda3\lib\site-packages (from pytesseract) (24.1)
Requirement already satisfied: Pillow>=8.0.0 in c:\users\admin\anaconda3\lib\site-packages (from pytesseract) (10.4.0)
Downloading pytesseract-0.3.13-py3-none-any.whl (14 kB)
Installing collected packages: pytesseract
Successfully installed pytesseract-0.3.13

In [10]:
#today night work

#!/usr/bin/env python3
"""
transaction_extractor.py

Extracts structured transaction data from a bank statements PDF.
If text extraction fails or PDF is image-only, uses OCR via pdf2image + pytesseract.

Outputs a CSV file with columns:
  date, time, amount, direction, counterparty, description, ref_id, category

Usage:
    python transaction_extractor.py <path_to_pdf> [--poppler-path <poppler_bin_path>]

Dependencies:
  - pymupdf (fitz): pip install pymupdf
  - pdf2image: pip install pdf2image
  - pytesseract: pip install pytesseract
  - pandas
  - re, os, sys, logging

Ensure Poppler is installed (on Windows extract poppler binaries, add poppler/bin to PATH or pass via --poppler-path).
Ensure Tesseract OCR is installed and pytesseract is configured.
"""

import fitz  # PyMuPDF
import re
import pandas as pd
import os
import sys
import argparse
import logging

def setup_logging():
    # Configure logging
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s [%(levelname)s] %(message)s',
        handlers=[
            logging.StreamHandler(sys.stdout)
        ]
    )

def print_raw_lines(pdf_path, pages_to_show=2, lines_to_show=30):
    """Print raw text lines so you can inspect actual formatting."""
    logging.info(f"Opening PDF for raw line inspection: {pdf_path}")
    try:
        doc = fitz.open(pdf_path)
    except Exception as e:
        logging.error(f"Could not open PDF: {e}")
        return

    for page_num in range(min(len(doc), pages_to_show)):
        page = doc[page_num]
        text = page.get_text("text")
        lines = text.splitlines()
        logging.info(f"\n--- Page {page_num+1} raw lines (first {lines_to_show}) ---")
        for i, line in enumerate(lines[:lines_to_show]):
            # show repr to reveal hidden characters/spaces
            logging.info(f"{i+1}: {repr(line)}")
    doc.close()

def extract_with_patterns_from_text(text, patterns):
    """Try multiple regex patterns over a block of text. Return list of matched groups."""
    rows = []
    for line in text.splitlines():
        for pat in patterns:
            m = re.search(pat, line)
            if m:
                rows.append(m.groups())
                break
    return rows

def extract_with_patterns(pdf_path, patterns):
    """Extract using text extraction (non-OCR)."""
    logging.info("Attempting text extraction (non-OCR)...")
    try:
        doc = fitz.open(pdf_path)
    except Exception as e:
        logging.error(f"Error opening PDF: {e}")
        return []

    rows = []
    for page in doc:
        try:
            text = page.get_text("text")
        except Exception as e:
            logging.warning(f"Error extracting text from a page: {e}")
            continue

        if not text or text.strip() == "":
            continue

        page_rows = extract_with_patterns_from_text(text, patterns)
        if page_rows:
            rows.extend(page_rows)

    doc.close()
    logging.info(f"Text extraction found {len(rows)} rows using patterns.")
    return rows

def try_ocr(pdf_path, patterns, poppler_path=None, dpi=200):
    """Fallback: OCR pages to text and extract using patterns."""
    logging.info("Starting OCR fallback...")
    try:
        from pdf2image import convert_from_path
        import pytesseract
    except ImportError as e:
        logging.error("OCR fallback unavailable. Make sure pdf2image and pytesseract are installed.")
        return []

    # If poppler_path is provided, pass it
    convert_kwargs = {}
    if poppler_path:
        convert_kwargs['poppler_path'] = poppler_path

    try:
        pages = convert_from_path(pdf_path, dpi=dpi, **convert_kwargs)
    except Exception as e:
        logging.error(f"Could not convert PDF to images for OCR: {e}")
        return []

    ocr_rows = []
    for i, page_image in enumerate(pages):
        try:
            txt = pytesseract.image_to_string(page_image)
        except Exception as e:
            logging.warning(f"Error during OCR on page {i+1}: {e}")
            continue

        logging.info(f"OCR page {i+1} first 10 lines: ")
        lines = txt.splitlines()
        for l in lines[:10]:
            logging.info(repr(l))

        # extract from OCR text
        page_rows = extract_with_patterns_from_text(txt, patterns)
        if page_rows:
            ocr_rows.extend(page_rows)

    logging.info(f"OCR extraction found {len(ocr_rows)} rows using patterns.")
    return ocr_rows

def normalize_rows(rows):
    """Normalize extracted tuples into dicts with known keys."""
    normalized = []
    for r in rows:
        # initialize all fields to None
        date = time = amount = direction = counterparty = description = ref_id = category = None

        # Different patterns produce different tuple lengths
        if len(r) >= 8:
            date, time, amount, direction, cp1, desc1, ref_id, category = r[:8]
            counterparty = cp1.strip() if cp1 else None
            description = desc1.strip() if desc1 else ""
        elif len(r) == 7:
            date, time, amount, direction, cp, ref_id, category = r
            counterparty = cp.strip()
            description = ""
        elif len(r) == 5:
            date, time, amount, direction, rest = r
            # attempt to split rest into cp / ref_id / category
            m = re.search(r"(.*?)(UTR\d+)([A-Za-z]+)$", rest)
            if m:
                counterparty_desc = m.group(1).strip()
                ref_id = m.group(2)
                category = m.group(3)
                if "Payment related to" in counterparty_desc:
                    parts = counterparty_desc.split("Payment related to")
                    counterparty = parts[0].strip()
                    description = "Payment related to " + parts[1].strip()
                else:
                    # simple heuristic
                    counterparty = counterparty_desc
                    description = ""
            else:
                counterparty = rest.strip()
                description = ""
        else:
            # fallback: join all as description
            joined = " | ".join([str(x) for x in r])
            date = r[0] if len(r) > 0 else None
            counterparty = joined
            description = joined

        normalized.append({
            "date": date,
            "time": time,
            "amount": amount,
            "direction": direction,
            "counterparty": counterparty,
            "description": description,
            "ref_id": ref_id,
            "category": category
        })
    return normalized

def parse_args():
    parser = argparse.ArgumentParser(description="Extract transactions from PDF (with OCR fallback)")
    parser.add_argument("pdf_path", help="Path to the PDF file containing transactions")
    parser.add_argument("--poppler-path", dest="poppler_path", default=None,
                        help="Path to Poppler bin folder (if not in system PATH)")
    parser.add_argument("--output", "-o", dest="output_csv", default="transactions_extracted.csv",
                        help="Name/path of output CSV file")
    parser.add_argument("--debug-inspect", dest="debug_inspect", action="store_true",
                        help="Print raw lines from PDF for inspection")
    parser.add_argument("--dpi", dest="dpi", type=int, default=200,
                        help="DPI resolution for OCR conversion (higher gives better OCR but slower)")
    return parser.parse_args()

def main():
    setup_logging()
    args = parse_args()

    pdf_path = args.pdf_path
    poppler_path = args.poppler_path
    output_csv = args.output_csv
    dpi = args.dpi

    # Check PDF file exists
    if not os.path.isfile(pdf_path):
        logging.error(f"PDF file not found: {pdf_path}")
        sys.exit(1)

    # Optional: inspect raw text to see formatting
    if args.debug_inspect:
        print_raw_lines(pdf_path, pages_to_show=2, lines_to_show=40)

    # Define regex patterns (modify as needed for your document format)
    patterns = [
        # Pattern 1: date, time, amount, direction, counterparty, optional "Payment related to", UTR, category
        r"(\d{2}-\d{2}-\d{4})\s+(\d{2}:\d{2})\s+([\d,]+(?:\.\d+)?)\s+(debit|credit)\s+(.*?)\s*(?:Payment related to\s*(.*?))?\s*(UTR\d+)\s*([A-Za-z]+)",
        # Pattern 2: description and UTR glued
        r"(\d{2}-\d{2}-\d{4})\s+(\d{2}:\d{2})\s+([\d,]+(?:\.\d+)?)\s+(debit|credit)\s+(.*?)(UTR\d+)([A-Za-z]+)",
        # Pattern 3: category at end
        r"(\d{2}-\d{2}-\d{4})\s+(\d{2}:\d{2})\s+([\d,]+(?:\.\d+)?)\s+(debit|credit)\s+(.*)\s+(UTR\d+)\s*([A-Za-z]+)$",
        # Pattern 4: minimal (no category/UTR)
        r"(\d{2}-\d{2}-\d{4})\s+(\d{2}:\d{2})\s+([\d,]+(?:\.\d+)?)\s+(debit|credit)\s+(.*)",
    ]

    # Step 1: Try normal text extraction
    rows = extract_with_patterns(pdf_path, patterns)

    # Step 2: If not enough matches, fallback to OCR
    if not rows or len(rows) < 5:
        logging.info("Text extraction gave insufficient results (rows < 5). Trying OCR fallback.")
        ocr_rows = try_ocr(pdf_path, patterns, poppler_path=poppler_path, dpi=dpi)
        if ocr_rows:
            rows = ocr_rows
        else:
            logging.error("After OCR fallback, still no matches found.")
            # Optionally exit or continue with whatever found
            if not rows:
                logging.error("No data to write. Exiting.")
                sys.exit(1)

    # Step 3: Normalize
    normalized = normalize_rows(rows)
    df = pd.DataFrame(normalized, columns=["date", "time", "amount", "direction",
                                           "counterparty", "description", "ref_id", "category"])

    # Clean amount: remove commas, convert to float
    def clean_amount(x):
        if x is None:
            return None
        try:
            # Remove commas
            s = str(x).replace(",", "")
            # Maybe it's integer or float
            return float(s)
        except ValueError:
            return None

    df["amount"] = df["amount"].apply(clean_amount)

    # Optional: drop rows with missing essential fields
    df_clean = df.dropna(subset=["date", "time", "amount", "direction"])

    # Save CSV
    logging.info(f"Saving output to: {output_csv}")
    try:
        df_clean.to_csv(output_csv, index=False)
    except Exception as e:
        logging.error(f"Error saving CSV: {e}")
        sys.exit(1)

    logging.info(f"Done. Extracted {len(df_clean)} transactions.")

if __name__ == "__main__":
    main()

usage: ipykernel_launcher.py [-h] [--poppler-path POPPLER_PATH]
                             [--output OUTPUT_CSV] [--debug-inspect]
                             [--dpi DPI]
                             pdf_path
ipykernel_launcher.py: error: the following arguments are required: pdf_path

SystemExit: 2

c:\Users\ADMIN\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py:3585: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

In [ ]:
#new code

In [4]:
!pip install pandas
!pip install pdfplumber
!pip install datetime
!pip install openai

Requirement already satisfied: pandas in c:\users\admin\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\admin\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: pdfplumber in c:\users\admin\anaconda3\lib\site-packages (0.11.7)
Requirement already satisfied: pdfminer.six==20250506 in c:\users\admin\anaconda3\lib\site-packages (from pdfplumber) (20250506)
Requirement already satisfied: Pillow>=9.1 in c:\users\admin\anaconda3\lib\site-packages (from pdfplumber) (10.4.0)
Requirement already satisfied: pypdfium2>=4.18.0 in c:\users\admin\anaconda3\lib\site-packages (from pdfplumber) (4.30.0)
Requirement already satisfied: charset-normalizer>=2.0.0 in c:\users\admin\anaconda3\lib\site-packages (from pdfminer.six==20250506->pdfplumber) (3.3.2)
Requirement already satisfied: cryptography>=36.0.0 in c:\users\admin\anaconda3\lib\site-packages (from pdfminer.six==20250506->pdfplumber) (43.0.0)
Requirement already satisfied: cffi>=1.12 in c:\users\admin\anaconda3\lib\site-packages (from cryptography>=36.0.0->pdfminer.six==20250506->pdfplumber) (1.17.1)
Requirement already satisfied: pycparser in c:\users\admin\anaconda3\lib\site-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six==20250506->pdfplumber) (2.21)
Requirement already satisfied: datetime in c:\users\admin\anaconda3\lib\site-packages (5.5)
Requirement already satisfied: zope.interface in c:\users\admin\anaconda3\lib\site-packages (from datetime) (5.4.0)
Requirement already satisfied: pytz in c:\users\admin\anaconda3\lib\site-packages (from datetime) (2024.1)
Requirement already satisfied: setuptools in c:\users\admin\anaconda3\lib\site-packages (from zope.interface->datetime) (75.1.0)
Collecting openai
  Downloading openai-1.107.3-py3-none-any.whl.metadata (29 kB)
Requirement already satisfied: anyio<5,>=3.5.0 in c:\users\admin\anaconda3\lib\site-packages (from openai) (4.2.0)
Requirement already satisfied: distro<2,>=1.7.0 in c:\users\admin\anaconda3\lib\site-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\admin\anaconda3\lib\site-packages (from openai) (0.27.0)
Collecting jiter<1,>=0.4.0 (from openai)
  Downloading jiter-0.11.0-cp312-cp312-win_amd64.whl.metadata (5.3 kB)
Requirement already satisfied: pydantic<3,>=1.9.0 in c:\users\admin\anaconda3\lib\site-packages (from openai) (2.8.2)
Requirement already satisfied: sniffio in c:\users\admin\anaconda3\lib\site-packages (from openai) (1.3.0)
Requirement already satisfied: tqdm>4 in c:\users\admin\anaconda3\lib\site-packages (from openai) (4.66.5)
Requirement already satisfied: typing-extensions<5,>=4.11 in c:\users\admin\anaconda3\lib\site-packages (from openai) (4.11.0)
Requirement already satisfied: idna>=2.8 in c:\users\admin\anaconda3\lib\site-packages (from anyio<5,>=3.5.0->openai) (3.7)
Requirement already satisfied: certifi in c:\users\admin\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->openai) (2025.4.26)
Requirement already satisfied: httpcore==1.* in c:\users\admin\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->openai) (1.0.2)
Requirement already satisfied: h11<0.15,>=0.13 in c:\users\admin\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.14.0)
Requirement already satisfied: annotated-types>=0.4.0 in c:\users\admin\anaconda3\lib\site-packages (from pydantic<3,>=1.9.0->openai) (0.6.0)
Requirement already satisfied: pydantic-core==2.20.1 in c:\users\admin\anaconda3\lib\site-packages (from pydantic<3,>=1.9.0->openai) (2.20.1)
Requirement already satisfied: colorama in c:\users\admin\anaconda3\lib\site-packages (from tqdm>4->openai) (0.4.6)
Downloading openai-1.107.3-py3-none-any.whl (947 kB)
   ---------------------------------------- 0.0/947.6 kB ? eta -:--:--
   ---------------------------------------- 947.6/947.6 kB 6.3 MB/s eta 0:00:00
Downloading jiter-0.11.0-cp312-cp312-win_amd64.whl (203 kB)
Installing collected packages: jiter, openai
Successfully installed jiter-0.11.0 openai-1.107.3

In [2]:
import re
from datetime import datetime
import pandas as pd
import pdfplumber
# optional: import fitz  # PyMuPDF if you prefer

DATE_FORMATS = [
    "%d-%m-%Y %H:%M", "%d-%m-%Y %H:%M:%S",
    "%d-%m-%Y", "%Y-%m-%d %H:%M", "%d/%m/%Y", "%d-%m-%Y %H:%M"
]

# Basic keyword -> category mapping (extendable)
CATEGORY_KEYWORDS = {
    "Shopping": ["flipkart", "amazon", "myntra", "snapdeal"],
    "Food": ["zomato", "swiggy", "dominos", "pizza", "restaurant", "dine"],
    "Transport": ["ola", "uber", "rapido", "taxi"],
    "Bills": ["airtel", "bsnl", "tneb", "electricity", "bill", "vodafone"],
    "Rent": ["house owner", "flat rent", "rent"],
    "Salary": ["company", "salary", "payroll"],
    "Investment": ["sbi securities", "mutual fund", "sip", "investment"],
    "Entertainment": ["hotstar", "netflix", "bookmyshow", "hotstar", "hotstar"],
    "Groceries": ["bigbasket", "blinkit", "zepto"],
    "Transfer": ["self account", "friend transfer"],
}

def guess_category(text):
    if pd.isna(text):
        return "Unknown"
    t = text.lower()
    for cat, keywords in CATEGORY_KEYWORDS.items():
        for kw in keywords:
            if kw in t:
                return cat
    # fallback heuristics
    if "credit" in t and "salary" in t: return "Salary"
    if "transfer" in t: return "Transfer"
    return "Other"

def parse_table_like_text(text):
    """
    If the PDF contains rows like:
    date time amount direction counterpart description ref_id category
    this function will attempt to parse lines into columns.
    """
    rows = []
    for line in text.splitlines():
        line = line.strip()
        if not line:
            continue
        # try to match: DATE TIME AMOUNT DIRECTION MERCHANT rest...
        # Many PDF exports are space-separated with no consistent delimiter; use regex
        # Example line (from your dataset): "02-09-2024 19:02 17734 debit Flipkart Payment related to FlipkartUTR100000Shopping"
        m = re.match(r"(\d{2}[-/]\d{2}[-/]\d{4})\s+(\d{1,2}:\d{2})\s+(\d+)\s+(\w+)\s+(.+)", line)
        if m:
            date_s, time_s, amount_s, direction, rest = m.groups()
            # attempt to split rest into merchant + description + maybe UTR + category
            # UTR and category may be jammed; try to find UTR like 'UTR\d+'
            utr = None
            utr_m = re.search(r"(UTR\d+)", rest)
            if utr_m:
                utr = utr_m.group(1)
                rest = rest.replace(utr, "").strip()
            # very simple merchant extraction: first token up to next capitalized word or 'Payment'
            parts = rest.split("Payment related to")
            if len(parts) == 2:
                merchant = parts[0].strip()
                description = parts[1].strip()
            else:
                tokens = rest.split()
                merchant = tokens[0]
                description = " ".join(tokens[1:]) if len(tokens) > 1 else ""
            rows.append({
                "date": date_s,
                "time": time_s,
                "amount": float(amount_s),
                "direction": direction,
                "merchant": merchant.strip(),
                "description": description.strip(),
                "utr": utr
            })
        else:
            # fallback: try splitting by multiple spaces
            toks = re.split(r"\s{2,}", line)
            if len(toks) >= 4:
                rows.append({
                    "date": toks[0],
                    "time": toks[1] if len(toks) > 1 else "",
                    "amount": float(re.sub(r"[^\d.]", "", toks[2])),
                    "direction": toks[3] if len(toks) > 3 else "",
                    "merchant": toks[4] if len(toks) > 4 else "",
                    "description": " ".join(toks[5:]) if len(toks) > 5 else ""
                })
            else:
                # ignore junk
                continue
    df = pd.DataFrame(rows)
    return df

def extract_text_from_pdf(path):
    """
    Use pdfplumber to extract text from all pages.
    Returns concatenated text.
    """
    texts = []
    with pdfplumber.open(path) as pdf:
        for page in pdf.pages:
            txt = page.extract_text()
            if txt:
                texts.append(txt)
    return "\n".join(texts)

def parse_pdf_to_df(path):
    """
    Master parser: extract text and try to parse table-like lines.
    """
    text = extract_text_from_pdf(path)
    # quick attempt: see if the file already contains a header 'date time amount'
    if re.search(r"\bdate\b.*\btime\b.*\bamount\b", text, re.I):
        # try to directly parse lines
        df = parse_table_like_text(text)
    else:
        # naive: split lines and attempt to parse
        df = parse_table_like_text(text)
    # normalize
    if df.empty:
        return df
    # try to combine date+time into datetime
    def parse_dt(row):
        s = f"{row.get('date','')} {row.get('time','')}".strip()
        for fmt in DATE_FORMATS:
            try:
                return datetime.strptime(s, fmt)
            except Exception:
                continue
        # fallback: try dd-mm-YYYY
        try:
            return datetime.strptime(row.get('date',''), "%d-%m-%Y")
        except Exception:
            return pd.NaT
    df['datetime'] = df.apply(parse_dt, axis=1)
    # fill merchant/description
    df['merchant'] = df['merchant'].astype(str).str.strip()
    df['description'] = df['description'].astype(str).str.strip()
    df['category'] = df.apply(lambda r: guess_category(" ".join([str(r['merchant']), str(r['description']), str(r.get('direction',''))])), axis=1)
    # normalize amount sign by direction
    df['amount_signed'] = df.apply(lambda r: -r['amount'] if str(r.get('direction','')).lower() in ['debit','dr'] else r['amount'], axis=1)
    # final columns
    df = df[['datetime','date','time','amount','amount_signed','direction','merchant','description','utr','category']]
    return df

In [5]:
import os
import openai

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
if OPENAI_API_KEY:
    openai.api_key = OPENAI_API_KEY

def get_recommendations(transactions_df, user_profile=None, model="gpt-4o-mini" ):
    """
    Build a concise prompt describing spending patterns and ask the LLM for advice.
    Returns text.
    """
    # build summary
    total_spent = transactions_df[transactions_df['amount_signed'] < 0]['amount'].sum()
    total_income = transactions_df[transactions_df['amount_signed'] > 0]['amount'].sum()
    top_categories = transactions_df.groupby('category')['amount'].sum().abs().sort_values(ascending=False).head(5).to_dict()
    recent = transactions_df.sort_values('datetime', ascending=False).head(10)[['datetime','merchant','amount','category']].to_dict(orient='records')

    prompt = f"""
You are a helpful personal finance assistant. A user gave their transaction data. Summary:
- total income: {total_income:.2f}
- total spending: {total_spent:.2f}
- top categories: {top_categories}
Provide: (1) a one-paragraph summary of their spending behavior, (2) 5 actionable recommendations to reduce unnecessary expenses and improve savings, (3) a suggested monthly budget split by category (percentages), and (4) any suspicious or wasteful transactions to watch out for based on top categories.

Recent transactions (latest 10): {recent}
Respond in plain text, numbered lists where appropriate.
"""
    # Use OpenAI (if key present)
    if OPENAI_API_KEY:
        try:
            resp = openai.ChatCompletion.create(
                model="gpt-4o-mini",  # change as per availability
                messages=[{"role":"user","content":prompt}],
                max_tokens=600,
                temperature=0.2
            )
            return resp['choices'][0]['message']['content'].strip()
        except Exception as e:
            return f"LLM call failed: {e}\n\nPrompt used:\n{prompt}"
    else:
        # fallback simple rule-based stub
        recs = ["(No API key set) Install OpenAI key to get personalized LLM recommendations.",
                "Rule: Reduce top discretionary category by 15% next month.",
                "Rule: Set auto-transfer to savings 10% of income.",
                "Rule: Review subscriptions (Entertainment) and cancel unused ones.",
                "Rule: Track weekly groceries & aim for 10% saving."]
        return "LLM not configured. Suggestions:\n" + "\n".join(f"- {r}" for r in recs)

In [6]:
!pip install streamlit
!pip install plotly
!pip install utils

Requirement already satisfied: streamlit in c:\users\admin\anaconda3\lib\site-packages (1.37.1)
Requirement already satisfied: altair<6,>=4.0 in c:\users\admin\anaconda3\lib\site-packages (from streamlit) (5.0.1)
Requirement already satisfied: blinker<2,>=1.0.0 in c:\users\admin\anaconda3\lib\site-packages (from streamlit) (1.6.2)
Requirement already satisfied: cachetools<6,>=4.0 in c:\users\admin\anaconda3\lib\site-packages (from streamlit) (5.3.3)
Requirement already satisfied: click<9,>=7.0 in c:\users\admin\anaconda3\lib\site-packages (from streamlit) (8.1.7)
Requirement already satisfied: numpy<3,>=1.20 in c:\users\admin\anaconda3\lib\site-packages (from streamlit) (1.26.4)
Requirement already satisfied: packaging<25,>=20 in c:\users\admin\anaconda3\lib\site-packages (from streamlit) (24.1)
Requirement already satisfied: pandas<3,>=1.3.0 in c:\users\admin\anaconda3\lib\site-packages (from streamlit) (2.2.2)
Requirement already satisfied: pillow<11,>=7.1.0 in c:\users\admin\anaconda3\lib\site-packages (from streamlit) (10.4.0)
Requirement already satisfied: protobuf<6,>=3.20 in c:\users\admin\anaconda3\lib\site-packages (from streamlit) (4.25.3)
Requirement already satisfied: pyarrow>=7.0 in c:\users\admin\anaconda3\lib\site-packages (from streamlit) (16.1.0)
Requirement already satisfied: requests<3,>=2.27 in c:\users\admin\anaconda3\lib\site-packages (from streamlit) (2.32.3)
Requirement already satisfied: rich<14,>=10.14.0 in c:\users\admin\anaconda3\lib\site-packages (from streamlit) (13.7.1)
Requirement already satisfied: tenacity<9,>=8.1.0 in c:\users\admin\anaconda3\lib\site-packages (from streamlit) (8.2.3)
Requirement already satisfied: toml<2,>=0.10.1 in c:\users\admin\anaconda3\lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.3.0 in c:\users\admin\anaconda3\lib\site-packages (from streamlit) (4.11.0)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\users\admin\anaconda3\lib\site-packages (from streamlit) (3.1.43)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in c:\users\admin\anaconda3\lib\site-packages (from streamlit) (0.8.0)
Requirement already satisfied: tornado<7,>=6.0.3 in c:\users\admin\anaconda3\lib\site-packages (from streamlit) (6.4.1)
Requirement already satisfied: watchdog<5,>=2.1.5 in c:\users\admin\anaconda3\lib\site-packages (from streamlit) (4.0.1)
Requirement already satisfied: jinja2 in c:\users\admin\anaconda3\lib\site-packages (from altair<6,>=4.0->streamlit) (3.1.4)
Requirement already satisfied: jsonschema>=3.0 in c:\users\admin\anaconda3\lib\site-packages (from altair<6,>=4.0->streamlit) (4.23.0)
Requirement already satisfied: toolz in c:\users\admin\anaconda3\lib\site-packages (from altair<6,>=4.0->streamlit) (0.12.0)
Requirement already satisfied: colorama in c:\users\admin\anaconda3\lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\admin\anaconda3\lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.7)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\anaconda3\lib\site-packages (from pandas<3,>=1.3.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\admin\anaconda3\lib\site-packages (from pandas<3,>=1.3.0->streamlit) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\admin\anaconda3\lib\site-packages (from pandas<3,>=1.3.0->streamlit) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\admin\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\admin\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\admin\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\admin\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (2025.4.26)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\admin\anaconda3\lib\site-packages (from rich<14,>=10.14.0->streamlit) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\admin\anaconda3\lib\site-packages (from rich<14,>=10.14.0->streamlit) (2.15.1)
Requirement already satisfied: smmap<5,>=3.0.1 in c:\users\admin\anaconda3\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\admin\anaconda3\lib\site-packages (from jinja2->altair<6,>=4.0->streamlit) (2.1.3)
Requirement already satisfied: attrs>=22.2.0 in c:\users\admin\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (23.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\admin\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\admin\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\admin\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.10.6)
Requirement already satisfied: mdurl~=0.1 in c:\users\admin\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich<14,>=10.14.0->streamlit) (0.1.0)
Requirement already satisfied: six>=1.5 in c:\users\admin\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.3.0->streamlit) (1.16.0)
Requirement already satisfied: plotly in c:\users\admin\anaconda3\lib\site-packages (5.24.1)
Requirement already satisfied: tenacity>=6.2.0 in c:\users\admin\anaconda3\lib\site-packages (from plotly) (8.2.3)
Requirement already satisfied: packaging in c:\users\admin\anaconda3\lib\site-packages (from plotly) (24.1)
Collecting utils
  Downloading utils-1.0.2.tar.gz (13 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: utils
  Building wheel for utils (setup.py): started
  Building wheel for utils (setup.py): finished with status 'done'
  Created wheel for utils: filename=utils-1.0.2-py2.py3-none-any.whl size=13936 sha256=24c11fed369f4c1f3659cd5ba271ea20461df06266bd7794693eee08bdb68b38
  Stored in directory: c:\users\admin\appdata\local\pip\cache\wheels\b6\a1\81\1036477786ae0e17b522f6f5a838f9bc4288d1016fc5d0e1ec
Successfully built utils
Installing collected packages: utils
Successfully installed utils-1.0.2

In [7]:
import streamlit as st
import pandas as pd
from io import BytesIO
import base64
# from utils import parse_pdf_to_df # Removed incorrect import
# from llm import get_recommendations # Removed incorrect import
import plotly.express as px

st.set_page_config(page_title="Personal UPI Analyzer", layout="wide")

st.title("Personal UPI Usage & Financial Analyzer")
st.markdown("Upload UPI PDF statement(s) (or the text dump) and get insights + LLM recommendations.")

uploaded = st.file_uploader("Upload one or more PDF statements or a CSV/text export", type=['pdf','txt','csv'], accept_multiple_files=True)

@st.cache_data
def process_files(files):
    dfs = []
    for f in files:
        if f.type == "application/pdf" or str(f.name).lower().endswith(".pdf"):
            # save temporarily to disk (or parse from bytes)
            bytes_data = f.read()
            # write to temp file
            tmp_path = f"/tmp/{f.name}"
            with open(tmp_path, "wb") as fh:
                fh.write(bytes_data)
            df = parse_pdf_to_df(tmp_path) # Use function defined in another cell
            df['source_file'] = f.name
            dfs.append(df)
        elif f.type == "text/csv" or str(f.name).lower().endswith(".csv"):
            df = pd.read_csv(f)
            dfs.append(df)
        else:
            # try reading bytes as text and parse
            raw = f.read().decode(errors='ignore')
            try:
                # try CSV parse
                df = pd.read_csv(BytesIO(raw.encode()))
                dfs.append(df)
            except Exception:
                # treat as text and attempt table parse via utils.parse_table_like_text
                # from utils import parse_table_like_text # Removed incorrect import
                df = parse_table_like_text(raw) # Use function defined in another cell
                dfs.append(df)
    if dfs:
        out = pd.concat(dfs, ignore_index=True, sort=False)
        return out
    else:
        return pd.DataFrame()

if uploaded:
    st.info(f"Processing {len(uploaded)} file(s)...")
    df = process_files(uploaded)
    if df.empty:
        st.error("Could not parse transactions. Try a different file or export your statement as text/CSV.")
    else:
        # Show preview
        st.subheader("Parsed transactions (preview)")
        st.dataframe(df.head(200))

        # Basic aggregations
        st.subheader("Summary")
        total_income = df[df['amount_signed'] > 0]['amount'].sum()
        total_spent = df[df['amount_signed'] < 0]['amount'].sum()
        st.metric("Total Income (sum credits)", f"{total_income:.2f}")
        st.metric("Total Spending (sum debits)", f"{abs(total_spent):.2f}")

        # Category breakdown
        st.subheader("Category breakdown")
        cat = df.groupby('category')['amount'].sum().abs().reset_index().sort_values(by='amount', ascending=False)
        fig = px.pie(cat, names='category', values='amount', title="Spending by category")
        st.plotly_chart(fig, use_container_width=True)

        # time series
        st.subheader("Spending over time")
        df_ts = df.copy()
        df_ts['date_only'] = pd.to_datetime(df_ts['datetime']).dt.to_period("M").astype(str)
        monthly = df_ts[df_ts['amount_signed']<0].groupby('date_only')['amount'].sum().abs().reset_index()
        if not monthly.empty:
            fig2 = px.bar(monthly, x='date_only', y='amount', title="Monthly spending")
            st.plotly_chart(fig2, use_container_width=True)

        # Top merchants
        st.subheader("Top merchants (by spend)")
        topm = df[df['amount_signed']<0].groupby('merchant')['amount'].sum().abs().reset_index().sort_values(by='amount', ascending=False).head(10)
        st.table(topm)

        # Allow download CSV
        csv = df.to_csv(index=False).encode()
        b64 = base64.b64encode(csv).decode()
        href = f'<a href="data:file/csv;base64,{b64}" download="transactions_parsed.csv">Download parsed CSV</a>'
        st.markdown(href, unsafe_allow_html=True)

        # Ask LLM for recommendations
        st.subheader("Personalized recommendations (LLM)")
        if st.button("Get LLM Recommendations"):
            with st.spinner("Generating recommendations..."):
                rec = get_recommendations(df) # Use function defined in another cell
                st.markdown("**LLM Recommendations**")
                st.write(rec)

        # Quick filters
        st.subheader("Filter transactions")
        c1, c2 = st.columns([2,1])
        with c1:
            merchant_filter = st.text_input("Merchant contains")
        with c2:
            cat_filter = st.selectbox("Category", options=["All"] + sorted(df['category'].dropna().unique().tolist()))
        filtered = df.copy()
        if merchant_filter:
            filtered = filtered[filtered['merchant'].str.contains(merchant_filter, case=False, na=False)]
        if cat_filter and cat_filter != "All":
            filtered = filtered[filtered['category'] == cat_filter]
        st.dataframe(filtered.head(200))
else:
    st.info("Upload your PDF statement(s) or the dataset (you uploaded earlier). Example dataset snippet (from your uploaded file):")
    st.code("See uploaded file snippet in project files. Example row: 02-09-2024 19:02 17734 debit Flipkart Payment related to Flipkart UTR100000 Shopping")
    st.markdown("When ready, upload the PDF(s) above to parse and analyze. The app will try to auto-detect columns and categorize transactions.")

2025-09-17 19:41:40.976
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run c:\Users\ADMIN\anaconda3\Lib\site-packages\ipykernel_launcher.py [ARGUMENTS]
2025-09-17 19:41:40.981 No runtime found, using MemoryCacheStorageManager

In [3]:
# app.py — Personal UPI Usage & Financial Analyzer (single-file)
# Run: streamlit run app.py

import re
import os
import tempfile
from datetime import datetime
from io import BytesIO
import base64

import pandas as pd
import pdfplumber

import streamlit as st
import plotly.express as px

# Optional: enable OpenAI LLM recommendations (set OPENAI_API_KEY as env var)
try:
    import openai
except Exception:
    openai = None

# ----------------------------
# Config & helper data
# ----------------------------
st.set_page_config(page_title="Personal UPI Analyzer", layout="wide")

DATE_FORMATS = [
    "%d-%m-%Y %H:%M", "%d-%m-%Y %H:%M:%S", "%d-%m-%Y",
    "%Y-%m-%d %H:%M", "%Y-%m-%d", "%d/%m/%Y",
    "%d-%m-%Y %H:%M"
]

CATEGORY_KEYWORDS = {
    "Shopping": ["flipkart", "amazon", "myntra", "snapdeal"],
    "Food": ["zomato", "swiggy", "dominos", "pizza", "restaurant", "dine"],
    "Transport": ["ola", "uber", "rapido", "taxi"],
    "Bills": ["airtel", "bsnl", "tneb", "electricity", "bill", "vodafone"],
    "Rent": ["house owner", "flat rent", "rent"],
    "Salary": ["company", "salary", "payroll"],
    "Investment": ["sbi securities", "mutual fund", "sip", "investment"],
    "Entertainment": ["hotstar", "netflix", "bookmyshow"],
    "Groceries": ["bigbasket", "blinkit", "zepto"],
    "Transfer": ["self account", "friend transfer", "transfer"],
}

DIRECTION_DEBIT = {"debit", "dr", "withdrawal", "sent", "paid"}
DIRECTION_CREDIT = {"credit", "cr", "received", "deposit", "refund"}

# ----------------------------
# Parsing helpers
# ----------------------------
def clean_amount_str(s):
    if s is None:
        return None
    s = str(s)
    # remove non-digit except dot and minus
    s = s.replace(",", "")
    m = re.search(r"-?\d+(\.\d+)?", s)
    return float(m.group(0)) if m else None

def guess_category(text):
    if not text or pd.isna(text):
        return "Unknown"
    t = str(text).lower()
    for cat, keywords in CATEGORY_KEYWORDS.items():
        for kw in keywords:
            if kw in t:
                return cat
    if "salary" in t or "payroll" in t: return "Salary"
    if "transfer" in t: return "Transfer"
    return "Other"

def extract_text_from_pdf_bytes(bytes_data):
    texts = []
    try:
        with pdfplumber.open(BytesIO(bytes_data)) as pdf:
            for page in pdf.pages:
                txt = page.extract_text()
                if txt:
                    texts.append(txt)
    except Exception as e:
        # file might be corrupt or scanned image; return empty
        st.warning(f"pdfplumber failed to read PDF: {e}")
    return "\n".join(texts)

def parse_table_like_text(text):
    """
    Flexible parser: tries several patterns and fallback heuristics.
    Returns dataframe with columns: date,time,amount,direction,merchant,description,utr
    """
    rows = []
    if not text:
        return pd.DataFrame(rows)

    for line in text.splitlines():
        line = line.strip()
        if not line:
            continue

        # normalize multiple spaces
        line_norm = re.sub(r"\s{2,}", "  ", line)

        # Pattern 1: dd-mm-yyyy [HH:MM] amount direction merchant ... (common)
        m = re.match(r"^(\d{1,2}[-/]\d{1,2}[-/]\d{4})\s+(\d{1,2}:\d{2})?\s+([-\d,\.]+)\s+([A-Za-z]+)\s+(.+)$", line_norm)
        if m:
            date_s, time_s, amount_s, direction, rest = m.groups()
            amt = clean_amount_str(amount_s)
            utr = None
            utr_m = re.search(r"(UTR[:\s]?[\w\d-]+)", rest, re.I)
            if utr_m:
                utr = utr_m.group(1)
                rest = rest.replace(utr, "").strip()
            # merchant heuristics: up to known keywords or 'Payment' words
            parts = re.split(r"\bPayment related to\b|\bfor\b|\b-+\b", rest, flags=re.I)
            merchant = parts[0].strip() if parts else ""
            description = parts[1].strip() if len(parts) > 1 else rest.replace(merchant, "").strip()
            rows.append({
                "date": date_s,
                "time": time_s if time_s else "",
                "amount": float(amt) if amt is not None else None,
                "direction": direction,
                "merchant": merchant,
                "description": description,
                "utr": utr
            })
            continue

        # Pattern 2: lines with 'debit'/'credit' anywhere and amount nearby
        if re.search(r"\b(debit|credit|dr|cr)\b", line, re.I) and re.search(r"\d[\d,\.]+\b", line):
            amt = clean_amount_str(line)
            dir_m = re.search(r"\b(debit|credit|dr|cr|paid|sent|received|deposit)\b", line, re.I)
            direction = dir_m.group(1) if dir_m else ""
            # attempt to extract date from line
            date_m = re.search(r"(\d{1,2}[-/]\d{1,2}[-/]\d{4})", line)
            time_m = re.search(r"(\d{1,2}:\d{2})", line)
            rest = line
            if date_m:
                rest = rest.replace(date_m.group(0), "")
            if time_m:
                rest = rest.replace(time_m.group(0), "")
            # best-effort merchant = first word chunk
            merchant = rest.split()[0] if rest.split() else ""
            description = rest.strip()
            rows.append({
                "date": date_m.group(0) if date_m else "",
                "time": time_m.group(0) if time_m else "",
                "amount": float(amt) if amt is not None else None,
                "direction": direction,
                "merchant": merchant,
                "description": description,
                "utr": None
            })
            continue

        # Fallback: try splitting by two or more spaces (table-like)
        toks = re.split(r"\s{2,}", line)
        if len(toks) >= 4:
            amt = clean_amount_str(toks[2])
            rows.append({
                "date": toks[0],
                "time": toks[1] if len(toks) > 1 else "",
                "amount": float(amt) if amt is not None else None,
                "direction": toks[3] if len(toks) > 3 else "",
                "merchant": toks[4] if len(toks) > 4 else "",
                "description": " ".join(toks[5:]) if len(toks) > 5 else ""
            })
            continue

        # otherwise: ignore noisy line
        continue

    df = pd.DataFrame(rows)
    return df

# ----------------------------
# Master parse + normalization
# ----------------------------
def parse_pdf_to_df_from_bytes(bytes_data):
    text = extract_text_from_pdf_bytes(bytes_data)
    df = parse_table_like_text(text)
    if df.empty:
        return df

    # standardize columns
    if 'amount' in df.columns:
        df['amount'] = pd.to_numeric(df['amount'], errors='coerce').fillna(0.0)
    else:
        df['amount'] = 0.0

    # combine date+time -> datetime
    def parse_dt(row):
        s = f"{row.get('date','')} {row.get('time','')}".strip()
        for fmt in DATE_FORMATS:
            try:
                return datetime.strptime(s, fmt)
            except Exception:
                continue
        # fallback: try date only heuristics
        for fmt in ["%d-%m-%Y", "%d/%m/%Y", "%Y-%m-%d"]:
            try:
                return datetime.strptime(row.get('date','') or '', fmt)
            except Exception:
                continue
        return pd.NaT

    df['datetime'] = df.apply(parse_dt, axis=1)

    # strip/normalize merchant & description
    for c in ['merchant','description','direction','utr']:
        if c in df.columns:
            df[c] = df[c].astype(str).str.strip().replace({'nan': ''})

    # category
    df['category'] = df.apply(lambda r: guess_category(" ".join([str(r.get('merchant','')), str(r.get('description','')), str(r.get('direction',''))])), axis=1)

    # amount_signed: debits negative
    def signed_amount(r):
        d = str(r.get('direction','')).lower()
        amt = r.get('amount', 0.0) or 0.0
        if any(x in d for x in DIRECTION_DEBIT):
            return -abs(amt)
        if any(x in d for x in DIRECTION_CREDIT):
            return abs(amt)
        # fallback heuristics using keywords in description
        desc = str(r.get('description','')).lower()
        if "received" in desc or "deposit" in desc:
            return abs(amt)
        return -abs(amt)  # assume spending if unclear

    df['amount_signed'] = df.apply(signed_amount, axis=1)

    # ensure final columns order
    final_cols = ['datetime','date','time','amount','amount_signed','direction','merchant','description','utr','category']
    for c in final_cols:
        if c not in df.columns:
            df[c] = ""
    df = df[final_cols]
    return df

# ----------------------------
# LLM recommendations helper
# ----------------------------
#api vaiable value
OPENAI_API_KEY = "sk-xxxxxxxxxxxxxxxxxxxxxxxx"
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
if OPENAI_API_KEY and openai:
    openai.api_key = OPENAI_API_KEY

def get_recommendations(transactions_df):
    # fallback: if no valid rows, return helpful message
    if transactions_df.empty:
        return "No transactions available to analyze."

    total_spent = transactions_df[transactions_df['amount_signed'] < 0]['amount'].abs().sum()
    total_income = transactions_df[transactions_df['amount_signed'] > 0]['amount'].sum()
    top_categories = transactions_df.groupby('category')['amount_signed'].sum().abs().sort_values(ascending=False).head(5).to_dict()
    recent = transactions_df.sort_values('datetime', ascending=False).head(10)[['datetime','merchant','amount_signed','category']].to_dict(orient='records')

    prompt = f"""
You are a helpful personal finance assistant. Summarize this user's spending data and give actionable recommendations.
Total income: {total_income:.2f}
Total spending: {total_spent:.2f}
Top categories: {top_categories}
Recent transactions: {recent}

Provide:
1) One-paragraph summary of spending behaviour.
2) Five actionable recommendations to reduce unnecessary expenses & improve savings.
3) Suggested monthly budget percentages by category.
4) Anything suspicious to review.
Respond concisely.
"""


    if OPENAI_API_KEY and openai:
        try:
            # use ChatCompletion if available; otherwise fallback
            resp = openai.ChatCompletion.create(
                model="gpt-4o-mini",
                messages=[{"role":"user","content":prompt}],
                max_tokens=600,
                temperature=0.2
            )
            return resp['choices'][0]['message']['content'].strip()
        except Exception as e:
            return f"LLM call failed: {e}\n\nPrompt used:\n{prompt}"
    else:
        # simple rule-based fallback
        recs = [
            "No OpenAI key set — set OPENAI_API_KEY env var for LLM suggestions.",
            "Reduce discretionary category by 10-20% next month.",
            "Set up auto-save: move fixed % of income to savings on payday.",
            "Review / cancel unused subscriptions in Entertainment.",
            "Compare grocery bills weekly & set a target."
        ]
        return "LLM not configured. Suggestions:\n" + "\n".join(f"- {r}" for r in recs)

# ----------------------------
# Streamlit UI
# ----------------------------
st.title("Personal UPI Usage & Financial Analyzer")
st.markdown("Upload UPI PDF statement(s) (or text/CSV). The app will try to parse transactions and provide insights.")

uploaded = st.file_uploader("Upload one or more PDF / CSV / TXT files", type=['pdf','csv','txt'], accept_multiple_files=True)

@st.cache_data
def process_files_streamlit(files):
    dfs = []
    for f in files:
        try:
            content = f.read()
            name = f.name
            if name.lower().endswith(".pdf") or getattr(f, "type", "") == "application/pdf":
                df = parse_pdf_to_df_from_bytes(content)
                if not df.empty:
                    df['source_file'] = name
                    dfs.append(df)
            elif name.lower().endswith(".csv") or getattr(f, "type","").startswith("text/csv"):
                try:
                    df = pd.read_csv(BytesIO(content))
                    dfs.append(df)
                except Exception as e:
                    st.warning(f"CSV read failed for {name}: {e}")
            else:
                # txt fallback
                try:
                    raw = content.decode(errors='ignore')
                except Exception:
                    raw = str(content)
                df = parse_table_like_text(raw)
                if not df.empty:
                    df['source_file'] = name
                    dfs.append(df)
        except Exception as e:
            st.error(f"Failed to process {f.name}: {e}")
    if dfs:
        out = pd.concat(dfs, ignore_index=True, sort=False)
        return out
    else:
        return pd.DataFrame()

if uploaded:
    with st.spinner("Parsing uploaded file(s)..."):
        df = process_files_streamlit(uploaded)
    if df.empty:
        st.error("Parsing produced no transactions. Try different statement export (CSV or text) or check sample format.")
    else:
        st.subheader("Parsed transactions (preview)")
        st.dataframe(df.head(200))

        # Summary metrics
        st.subheader("Summary")
        total_income = df[df['amount_signed'] > 0]['amount'].sum()
        total_spent = df[df['amount_signed'] < 0]['amount'].abs().sum()
        col1, col2 = st.columns(2)
        col1.metric("Total Income (sum credits)", f"{total_income:.2f}")
        col2.metric("Total Spending (sum debits)", f"{total_spent:.2f}")

        # Category breakdown (pie)
        st.subheader("Category breakdown")
        cat = df.groupby('category')['amount'].sum().abs().reset_index().sort_values(by='amount', ascending=False)
        if not cat.empty:
            fig = px.pie(cat, names='category', values='amount', title="Spending by category")
            st.plotly_chart(fig, use_container_width=True)

        # Monthly timeseries
        st.subheader("Spending over time")
        df_ts = df.copy()
        # make sure datetime column is proper
        df_ts['datetime'] = pd.to_datetime(df_ts['datetime'], errors='coerce')
        df_ts['month'] = df_ts['datetime'].dt.to_period("M").astype(str)
        monthly = df_ts[df_ts['amount_signed']<0].groupby('month')['amount_signed'].sum().abs().reset_index().sort_values('month')
        if not monthly.empty:
            fig2 = px.bar(monthly, x='month', y='amount_signed', labels={'amount_signed':'amount'}, title="Monthly spending")
            st.plotly_chart(fig2, use_container_width=True)
        else:
            st.info("No monthly spending data to show (datetime parsing may have failed).")

        # Top merchants
        st.subheader("Top merchants (by spend)")
        topm = df[df['amount_signed']<0].groupby('merchant')['amount_signed'].sum().abs().reset_index().sort_values(by='amount_signed', ascending=False).head(10)
        if not topm.empty:
            st.table(topm)
        else:
            st.info("No merchant spend data found.")

        # Download parsed CSV
        csv = df.to_csv(index=False).encode()
        b64 = base64.b64encode(csv).decode()
        href = f'<a href="data:file/csv;base64,{b64}" download="transactions_parsed.csv">Download parsed CSV</a>'
        st.markdown(href, unsafe_allow_html=True)

        # Filters
        st.subheader("Filter transactions")
        c1, c2 = st.columns([2,1])
        with c1:
            merchant_filter = st.text_input("Merchant contains")
        with c2:
            cat_options = ["All"] + sorted(df['category'].dropna().unique().tolist())
            cat_filter = st.selectbox("Category", options=cat_options)
        filtered = df.copy()
        if merchant_filter:
            filtered = filtered[filtered['merchant'].str.contains(merchant_filter, case=False, na=False)]
        if cat_filter and cat_filter != "All":
            filtered = filtered[filtered['category'] == cat_filter]
        st.dataframe(filtered.head(200))

        # LLM Recommendations
        st.subheader("Personalized recommendations (LLM)")
        if st.button("Get LLM Recommendations"):
            with st.spinner("Generating recommendations..."):
                rec = get_recommendations(df)
                st.markdown("**LLM Recommendations**")
                st.write(rec)
else:
    st.info("Upload your PDF statement(s) or a CSV/text export. Example row format:\n\n`02-09-2024 19:02 17734 debit Flipkart Payment related to Flipkart UTR100000 Shopping`")

# ----------------------------
# End
# ----------------------------

2025-09-18 01:33:37.017 No runtime found, using MemoryCacheStorageManager

In [9]:
streamlit run app.py

SyntaxError: invalid syntax (507122745.py, line 1)